# Generated by Django 3.0.3 on 2020-02-26 19:59

import collection.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=collection.models.get_adminpic_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameDLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=collection.models.get_adminpic_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=collection.models.get_adminpic_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compilation', models.ManyToManyField(blank=True, related_name='games_id', to='collection.Compilation')),
            ],
        ),
        migrations.CreateModel(
            name='Plateform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=collection.models.get_adminpic_path)),
                ('region', models.IntegerField(choices=[(1, 'Europe'), (2, 'Amerique Du Nord'), (3, 'Japon'), (4, 'Amerique Central'), (5, 'Amerique Du Sud'), (6, 'Asie'), (7, 'Russie'), (8, 'Moyen Orient'), (9, 'Afrique')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlateformAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=collection.models.get_adminpic_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plateform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Plateform')),
            ],
        ),
        migrations.CreateModel(
            name='SubPlateform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to=collection.models.get_adminpic_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plateform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Plateform')),
            ],
        ),
        migrations.CreateModel(
            name='UserOwnedCompilation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compilation_name', models.CharField(max_length=200)),
                ('physical', models.BooleanField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=collection.models.get_userpic_path)),
                ('box_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('covers_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('manual_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('game_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('condition_precision', models.TextField(blank=True, null=True)),
                ('owning_status', models.IntegerField(choices=[(1, 'Possede'), (2, 'Vendu'), (3, 'Donnee'), (4, 'Pret Dun Ami'), (5, 'Abonement'), (6, 'Autre')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compilation_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Compilation')),
                ('plateform_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Plateform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOwnedGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('physical', models.BooleanField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=collection.models.get_userpic_path)),
                ('box_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('covers_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('manual_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('game_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('condition_precision', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rating_precision', models.TextField(blank=True, null=True)),
                ('never_played', models.BooleanField()),
                ('completion_status', models.IntegerField(choices=[(1, 'Pas Fini'), (2, 'Fini'), (3, 'Fini Cent Pour Cent'), (4, 'Sans Fin'), (5, 'Abandonne')])),
                ('completion_precision', models.TextField(blank=True, null=True)),
                ('achievements_earned', models.IntegerField(blank=True, null=True)),
                ('achievements_to_be_earned', models.IntegerField(blank=True, null=True)),
                ('owning_status', models.IntegerField(choices=[(1, 'Possede'), (2, 'Vendu'), (3, 'Donnee'), (4, 'Pret Dun Ami'), (5, 'Abonement'), (6, 'Autre')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compilation', models.ManyToManyField(blank=True, related_name='userownedgame_id', to='collection.UserOwnedCompilation')),
                ('game_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Games')),
                ('plateform_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Plateform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOwnedSubPlateform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=collection.models.get_userpic_path)),
                ('box_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('covers_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('manual_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('subplateform_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('condition_precision', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subplateform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.SubPlateform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOwnedPlateformAddon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=collection.models.get_userpic_path)),
                ('box_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('covers_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('manual_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('plateformaddon_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('condition_precision', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plateformaddon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.PlateformAddon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOwnedGameDLC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamedlc_name', models.CharField(max_length=200)),
                ('physical', models.BooleanField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=collection.models.get_userpic_path)),
                ('box_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('covers_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('manual_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('gamedlc_condition', models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Tres Bon'), (6, 'Neuf')], null=True)),
                ('condition_precision', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('rating_precision', models.TextField(blank=True, null=True)),
                ('owning_status', models.IntegerField(choices=[(1, 'Possede'), (2, 'Vendu'), (3, 'Donnee'), (4, 'Pret Dun Ami'), (5, 'Abonement'), (6, 'Autre')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gamedlc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.GameDLC')),
                ('gameowned_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.UserOwnedGame')),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profil_picture', models.ImageField(blank=True, null=True, upload_to=collection.models.get_userpic_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='games',
            name='plateform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.SubPlateform'),
        ),
        migrations.AddField(
            model_name='gamedlc',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Games'),
        ),
        migrations.AddField(
            model_name='compilation',
            name='plateform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.SubPlateform'),
        ),
        migrations.CreateModel(
            name='CollectionPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_picture', models.ImageField(blank=True, null=True, upload_to=collection.models.get_userpic_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
