# Generated by Django 3.0.3 on 2020-03-06 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilation',
            name='plateform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Plateform'),
        ),
        migrations.AlterField(
            model_name='games',
            name='plateform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Plateform'),
        ),
    ]
