# Generated by Django 3.0.3 on 2020-03-06 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20200306_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userownedgame',
            name='compilation',
        ),
        migrations.AddField(
            model_name='userownedgame',
            name='compilation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.Compilation'),
        ),
    ]
