# Generated by Django 3.0.3 on 2020-03-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20200306_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plateform',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='plateformaddon',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='subplateform',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='userownedcompilation',
            name='box_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedcompilation',
            name='covers_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedcompilation',
            name='game_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedcompilation',
            name='manual_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedcompilation',
            name='owning_status',
            field=models.IntegerField(choices=[(1, 'Possédé'), (2, 'Vendu'), (3, 'Donné'), (4, "Pret d'un ami"), (5, 'Abonnement'), (6, 'Autre')]),
        ),
        migrations.AlterField(
            model_name='userownedgame',
            name='box_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedgame',
            name='covers_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedgame',
            name='game_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedgame',
            name='manual_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedgame',
            name='owning_status',
            field=models.IntegerField(choices=[(1, 'Possédé'), (2, 'Vendu'), (3, 'Donné'), (4, "Pret d'un ami"), (5, 'Abonnement'), (6, 'Autre')]),
        ),
        migrations.AlterField(
            model_name='userownedgame',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '0'), (2, '1'), (3, '2'), (4, '3'), (5, '4'), (6, '5'), (7, '6'), (8, '7'), (9, '8'), (10, '9'), (11, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedgamedlc',
            name='box_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedgamedlc',
            name='covers_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedgamedlc',
            name='gamedlc_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedgamedlc',
            name='manual_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedgamedlc',
            name='owning_status',
            field=models.IntegerField(choices=[(1, 'Possédé'), (2, 'Vendu'), (3, 'Donné'), (4, "Pret d'un ami"), (5, 'Abonnement'), (6, 'Autre')]),
        ),
        migrations.AlterField(
            model_name='userownedgamedlc',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '0'), (2, '1'), (3, '2'), (4, '3'), (5, '4'), (6, '5'), (7, '6'), (8, '7'), (9, '8'), (10, '9'), (11, '10')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedplateformaddon',
            name='box_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedplateformaddon',
            name='covers_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedplateformaddon',
            name='manual_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedplateformaddon',
            name='plateformaddon_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedsubplateform',
            name='box_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedsubplateform',
            name='covers_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedsubplateform',
            name='manual_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
        migrations.AlterField(
            model_name='userownedsubplateform',
            name='subplateform_condition',
            field=models.IntegerField(blank=True, choices=[(1, 'Manquant'), (2, 'Mauvais'), (3, 'Moyen'), (4, 'Bon'), (5, 'Très Bon'), (6, 'Neuf')], null=True),
        ),
    ]
