# Generated by Django 3.0.3 on 2020-03-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_auto_20200309_0544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userownedplateformaddon',
            name='covers_condition',
        ),
        migrations.RemoveField(
            model_name='userownedsubplateform',
            name='covers_condition',
        ),
        migrations.AddField(
            model_name='collectionpicture',
            name='private',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plateform',
            name='region',
            field=models.IntegerField(choices=[(1, 'Europe'), (2, 'Amérique du Nord'), (3, 'Japon'), (4, 'Amérique Central'), (5, 'Amérique du Sud'), (6, 'Asie'), (7, 'Russie'), (8, 'Moyen Orient'), (9, 'Afrique')]),
        ),
        migrations.AlterField(
            model_name='userownedgame',
            name='completion_status',
            field=models.IntegerField(choices=[(1, 'Pas fini'), (2, 'Fini'), (3, 'Fini à 100%'), (4, "N'a pas de fin"), (5, 'Abandonné')]),
        ),
    ]
