# Generated by Django 3.0.3 on 2020-03-10 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20200310_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='games',
            name='compilation',
        ),
        migrations.AlterField(
            model_name='userownedgame',
            name='compilation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collection.UserOwnedCompilation'),
        ),
    ]
