# Generated by Django 3.0.3 on 2020-03-23 22:32

import collection.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collection', '0008_auto_20200310_0405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamedlc',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='userownedcompilation',
            options={'ordering': ('compilation_name',)},
        ),
        migrations.AlterModelOptions(
            name='userownedgame',
            options={'ordering': ('game_name',)},
        ),
        migrations.AddField(
            model_name='userownedgamedlc',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectionpicture',
            name='collection_picture',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.get_userpic_path, validators=[collection.models.validate_picture]),
        ),
        migrations.AlterField(
            model_name='plateform',
            name='region',
            field=models.IntegerField(choices=[(1, 'Europe'), (2, 'Amérique du Nord'), (3, 'Japon'), (4, 'Amérique Central'), (5, 'Amérique du Sud'), (6, 'Asie'), (7, 'Russie'), (8, 'Moyen Orient'), (9, 'Afrique'), (10, 'Monde')]),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='profil_picture',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.get_userpic_path, validators=[collection.models.validate_picture]),
        ),
        migrations.AlterField(
            model_name='userownedcompilation',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.get_userpic_path, validators=[collection.models.validate_picture]),
        ),
        migrations.AlterField(
            model_name='userownedgame',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.get_userpic_path, validators=[collection.models.validate_picture]),
        ),
        migrations.AlterField(
            model_name='userownedgamedlc',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.get_userpic_path, validators=[collection.models.validate_picture]),
        ),
        migrations.AlterField(
            model_name='userownedplateformaddon',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.get_userpic_path, validators=[collection.models.validate_picture]),
        ),
        migrations.AlterField(
            model_name='userownedsubplateform',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=collection.models.get_userpic_path, validators=[collection.models.validate_picture]),
        ),
    ]
